[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dll"
version = "0.1.0"
description = "Doubly Linked List implementation in Python"
authors = [
    { name="Ahmedhm1", email="ahhi9014@email.com" }
]
license = { text = "MIT" }
dependencies = []
